{
 "title": "Homework",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Свободное место на файловой системе",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", fstype!=\"\"} / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Свободная оперативная память",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "утилизация CPU для nodeexporter (в процентах, 100-idle);",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "node_load1\r", "legendFormat": "Load 1m" },
    { "expr": "node_load5", "legendFormat": "Load 5m" },
    { "expr": "node_load15", "legendFormat": "Load 15m" }
   ]
  }
 ]
}